spring.application.name=SpringOAtuh2Demo
server.port=9090

spring.security.oauth2.client.registration.github.client-id=Ov23lizDKMWr9jrgUwwn
spring.security.oauth2.client.registration.github.client-secret=4f76cbf854dd5005970fd832f5febce68234272f


