spring.application.name=SpringOAtuh2Demo
server.port=9091

spring.security.oauth2.client.registration.github.client-id=Ov23li2mOSZWuVhr7z5o
spring.security.oauth2.client.registration.github.client-secret=6850ff6892470e262e801616a0a2d134bbc377ba


